import '@/styles/globals.css'

export const metadata = {
  title: 'Fidoo Technical Test',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  /** Los componentes hijo que se renderizarán dentro del diseño. */
  children: React.ReactNode
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='es'>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
