import '@/styles/globals.css'

export const metadata = {
  title: 'Fidoo Technical Test',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
